### ISSUE TITLE
App closes as soon as it opens.

### ISSUE THREAD

**Issue by supersuryaansh** [holepunchto/pear-expo-hello-world#8]
I have followed the instructions correctly step by step, and not made any change to the hello world pear expo application. Trying to run it in Android emulator on my Mac air M2, it closes as soon as it launches.

I was able to retrieve this error from logcat:

2024-03-23 12:11:25.184 10415-10488 libc                    to.holepunch.hellopear.app           A  Fatal signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0x6bed0faaa8 in tid 10488 (mqt_js), pid 10415 (h.hellopear.app)

Any idea how to get this to work and what might be causing this?

**Comment by n9lsjr** [comment]
Same here, it does not work at all. App closes on start. `HelloBare module not found` is sometimes displayed in the debugger.
Got this problem on both Windows and Intel Mac emulators. ( And phone )

**Comment by n9lsjr** [comment]
After some investigation it seems like i got this error: 
![image](https://github.com/holepunchto/pear-expo-hello-world/assets/64911460/90d4034d-4908-4962-a29b-bab6902ae466)

I noticed there was a PR solving this issue but after copying the updated file  (and re-running hello-pear) I still got the same error.

**Comment by n9lsjr** [comment]
After some more troubleshooting I ended up manually updating the bare module (and submodules) files because it seemd like the handler error was fixed.

I added some logs to the `bare/hello-bare.cc` file in the project to se where in the process it crashed next time:

![image](https://github.com/holepunchto/pear-expo-hello-world/assets/64911460/552f0275-795b-4ebb-9288-9bef596f8d73)

![image](https://github.com/holepunchto/pear-expo-hello-world/assets/64911460/204d53f2-02a1-40b0-999f-0ddc5ee65f89)

This might be casued by my hacking.  I will try starting from scratch with updated modules and reproduce this 👍

**Comment by n9lsjr** [comment]
@supersuryaansh ***SOLVED*** I manually updated the `vendor/bare` module and the submodules `bare\vendor\libutf`  `bare\vendor\libjs`  etc..

![image](https://github.com/holepunchto/pear-expo-hello-world/assets/64911460/a4ed8a57-d3df-4d88-8d94-cde621183247)

**Comment by supersuryaansh** [comment]
@n9lsjr Thanks for the info mate, I saw a similar solution in the bare-developers channel on Keet but forgot to check it. This should work.
